'use strict';
const library=window.ICON_LIBRARY, catalog=library.catalog;
let prefs=library.preferences,provider='',visible=60,current=null,currentVariant=null,connected=false,toastTimer;
const $=id=>document.getElementById(id), labels={aliyun:'阿里云',aws:'AWS',opensource:'开源组件',tencent:'腾讯云',huawei:'华为云',generic:'通用组件',status:'状态符号',unclassified:'待分类'};
const allVariants=new Map(catalog.products.map(p=>[p.id,catalog.variants.filter(v=>v.product_id===p.id)]));
const variantMap=new Map(catalog.variants.map(v=>[v.id,v]));
const featured=['aliyun/ecs','aliyun/oss','aliyun/rds','aliyun/redis','aliyun/mse','aliyun/container-service','aws/ec2','aws/s3','aws/lambda','aws/rds','aws/eks','aws/dynamodb','opensource/doris','opensource/postgresql','opensource/rocketmq'];
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function selected(p){return variantMap.get(prefs.defaults[p.id]||p.default_variant)||allVariants.get(p.id)[0];}
function image(v,size){const img=el('img',v.theme.dark_backdrop?'needs-backdrop':'');img.src='../'+v.asset.path;img.alt='';img.loading='lazy';if(size)img.width=size;return img;}
function message(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3000);}
async function copy(text){try{await navigator.clipboard.writeText(text);}catch{const t=el('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}message('已复制');}
function providerNavigation(){const nav=$('providers');nav.replaceChildren();for(const [id,title] of [['','全部图标'],...Object.entries(labels)]){const count=catalog.products.filter(p=>(!id||p.provider===id)&&($('pending').checked||p.status==='ready')).length;if(id&&!catalog.products.some(p=>p.provider===id))continue;const b=el('button',provider===id?'active':'');b.type='button';b.setAttribute('aria-pressed',String(provider===id));b.append(el('span','provider-mark',id==='aws'?'aws':id==='aliyun'?'云':id==='opensource'?'</>':id==='generic'?'◇':id==='status'?'✓':'▦'),el('span','',title),el('span','count',String(count)));b.onclick=()=>{provider=id;visible=60;updateCategories();render();};nav.append(b);}}
function updateCategories(){const old=$('category').value;const list=[...new Set(catalog.products.filter(p=>!provider||p.provider===provider).map(p=>p.category))].sort((a,b)=>a.localeCompare(b));$('category').replaceChildren(new Option('全部分类',''));for(const c of list)$('category').add(new Option(c,c));if(list.includes(old))$('category').value=old;}
function normalized(s){return s.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');}
function results(){const q=$('search').value.trim().toLowerCase(),tokens=q.split(/\s+/).map(normalized).filter(Boolean);return catalog.products.filter(p=>{if(provider&&p.provider!==provider)return false;if(!$('pending').checked&&p.status!=='ready')return false;if($('category').value&&p.category!==$('category').value)return false;if($('kind').value&&p.kind!==$('kind').value)return false;const hay=[p.id,p.name,...p.aliases].map(normalized);return tokens.every(t=>hay.some(s=>s.includes(t)));}).sort((a,b)=>{const x=featured.indexOf(a.id),y=featured.indexOf(b.id);return (x<0?999:x)-(y<0?999:y)||a.name.localeCompare(b.name);});}
function render(){providerNavigation();const list=results();$('results').textContent=`${list.length.toLocaleString()} 个结果`;$('collection-label').textContent=provider?(labels[provider]||provider):'全部图标';const frag=document.createDocumentFragment();for(const p of list.slice(0,visible)){const vs=allVariants.get(p.id),v=selected(p),button=el('button','icon-card');button.type='button';button.setAttribute('aria-label','查看 '+p.name+'，'+(labels[p.provider]||p.provider));button.dataset.product=p.id;const stage=el('div','icon-stage');stage.append(image(v));if(vs.length>1)stage.append(el('span','mini-label',vs.length+' 个变体'));if(p.status==='pending')stage.append(el('span','pending-badge','待确认'));const txt=el('div','card-label');txt.append(el('strong','',p.name),el('small','',(labels[p.provider]||p.provider)+' · '+p.category));button.append(stage,txt);button.onclick=()=>openDetails(p);frag.append(button);}$('grid').replaceChildren(frag);$('empty').hidden=!!list.length;$('more').hidden=visible>=list.length;}
function openDetails(p){current=p;currentVariant=selected(p);$('review-current').hidden=!allVariants.get(p.id).some(v=>v.status==='pending');$('detail-provider').textContent=(labels[p.provider]||p.provider)+' / ICON DETAILS';$('detail-name').textContent=p.name;$('detail-id').textContent=p.id;$('detail-category').textContent=p.category+' · '+({'product':'产品与资源','brand':'品牌','component':'通用组件','container-symbol':'边界标识','status':'状态符号'}[p.kind]||p.kind);$('detail-aliases').textContent=p.aliases.join(' · ');$('detail-note').textContent=p.notes.join(' ');$('detail-status').textContent=p.status==='ready'?'可供自动选择 · 真实矢量':'待确认 · 不参与自动选择';$('detail-status').className='tag'+(p.status==='pending'?' pending':'');$('variant-total').textContent=allVariants.get(p.id).length+' 个';refreshDetails();$('details').showModal();}
function refreshDetails(){const p=current,v=currentVariant;for(const id of ['light-image','dark-image']){$(id).src='../'+v.asset.path;$(id).alt=p.name;} $('download').href='../'+v.asset.path;$('download').download=p.id.replace('/','-')+'-'+v.style+'.svg';$('detail-source').textContent=v.origins.map(o=>o.path+' · '+o.entry).join('\n');$('variants').replaceChildren();const chosen=prefs.defaults[p.id]||p.default_variant;for(const x of allVariants.get(p.id)){const b=el('button','variant'+(x.id===v.id?' selected':''));b.type='button';b.dataset.variant=x.id;b.setAttribute('aria-pressed',String(x.id===v.id));b.append(image(x),el('span','',x.style+(x.status==='pending'?' · 待确认':'')+(chosen===x.id?' · 默认':'')));b.onclick=()=>{currentVariant=x;refreshDetails();};$('variants').append(b);}const ready=p.status==='ready'&&v.status==='ready';$('prefer').disabled=!ready;$('prefer').textContent=connected?(v.id===chosen?'当前默认图标':'设为默认图标'):'复制设为默认命令';$('reset').disabled=!connected||!prefs.defaults[p.id];$('preference-help').textContent=connected?'默认选择保存到项目配置，Agent 查询会使用同一设置。':'当前为静态预览。可复制命令设置默认，或启动本地预览服务直接保存。';}
$('prefer').onclick=async()=>{if(!current)return;if(!connected){await copy('python3 '+library.root_path+'/scripts/iconlib.py prefer '+current.id+' '+currentVariant.id);return;}try{const r=await fetch('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:current.id,variant_id:currentVariant.id})});const data=await r.json();if(!r.ok)throw Error(data.error);prefs=data;refreshDetails();render();message('已保存默认图标，Agent 查询同步生效');}catch(e){message('保存失败：'+e.message);}};
$('reset').onclick=async()=>{try{const r=await fetch('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:current.id,variant_id:null})});const data=await r.json();if(!r.ok)throw Error(data.error);prefs=data;currentVariant=selected(current);refreshDetails();render();message('已恢复目录默认');}catch(e){message('保存失败：'+e.message);}};
$('copy-id').onclick=()=>copy(current.id);$('close').onclick=()=>$('details').close();$('details').addEventListener('click',e=>{if(e.target===$('details')){const r=$('details').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('details').close();}});
$('theme').onclick=()=>{document.body.classList.toggle('dark');$('theme').textContent=document.body.classList.contains('dark')?'◐ 浅色预览':'◐ 深色预览';};
for(const id of ['search','category','kind','pending'])$(id).addEventListener(id==='search'?'input':'change',()=>{visible=60;render();});
$('more').onclick=()=>{visible+=60;render();};$('clear').onclick=()=>{provider='';$('search').value='';$('category').value='';$('kind').value='';$('pending').checked=false;visible=60;updateCategories();render();};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('search').focus();}});
$('product-count').textContent=catalog.products.length.toLocaleString();$('variant-count').textContent=catalog.variants.length.toLocaleString();updateReviewCount();
for(const p of catalog.products)if(!labels[p.provider])labels[p.provider]=p.provider;
updateCategories();render();
if(location.protocol.startsWith('http'))fetch('/api/preferences').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{prefs=data;connected=true;$('mode').textContent='本地预览 · 默认选择已同步';render();}).catch(()=>{$('mode').textContent='静态预览 · 支持下载与查询';});else $('mode').textContent='离线预览 · 支持下载与查询';

async function reloadCatalog(){
 const [c,p]=await Promise.all([fetch('/api/catalog').then(r=>r.json()),fetch('/api/preferences').then(r=>r.json())]);
 catalog.products=c.products;catalog.variants=c.variants;prefs=p;
 allVariants.clear();variantMap.clear();
 for(const v of c.variants){variantMap.set(v.id,v);if(!allVariants.has(v.product_id))allVariants.set(v.product_id,[]);allVariants.get(v.product_id).push(v);}
 for(const p of c.products)if(!labels[p.provider])labels[p.provider]=p.provider;
 $('product-count').textContent=c.products.length.toLocaleString();$('variant-count').textContent=c.variants.length.toLocaleString();updateReviewCount();
 provider='';$('search').value='';$('kind').value='';$('category').value='';$('pending').checked=true;visible=60;updateCategories();render();
}

function updateReviewCount(){const count=new Set(catalog.variants.filter(v=>v.status==='pending').map(v=>v.product_id)).size;$('pending-count').textContent=count;$('open-review').textContent='待确认审核 · '+count;}
$('review-current').onclick=()=>{const id=current.id;$('details').close();window.openIconReview(id);};
